version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: threaddit_postgres
    environment:
      POSTGRES_DB: final_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kjkszpj706
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: threaddit_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/final_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Kjkszpj706
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    ports:
      - "8080:8080"
    restart: always

volumes:
  pg_data:
